# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu1804"

  config.vm.provider "hyperv" do |hv|
    hv.memory = 2048
    hv.vmname = "Ubuntu-RubyOnRails"
    hv.cpus = 2
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.name = "Ubuntu-180-with-Rails"
    vb.cpus = 2
  end


  config.vm.provision "file", source: "./buildup.sh", destination: "~/buildup.sh"

  config.vm.provision "shell", path: './buildup.sh'

  config.vm.provision "shell", inline: <<-SHELL
     echo "OH HEY WE'RE DONE"
  SHELL
end
